trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: RunTestsAndUploadAllureReport
  timeoutInMinutes: 60
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
    displayName: 'Set up Python 3.11'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install --with-deps
      wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
      tar -zxvf allure-2.25.0.tgz
      sudo cp -R allure-2.25.0/bin /usr/bin/allure
      export PATH=$PATH:/usr/bin/allure/bin
    displayName: 'Install dependencies'

  - script: |
      pytest
      ls -la
      ls -la reports/
    displayName: 'Run tests and Generate Allure Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'reports/allure-results'
      artifactName: 'allure-results'
    displayName: 'Archive Allure Report Results'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'reports/videos'
      artifactName: 'videos'
    displayName: 'Archive Playwright Videos'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'logs/trace.zip'
      artifactName: 'trace-logs'
    displayName: 'Archive Trace Logs'
