trigger:
  - master

pool:
  vmImage: ubuntu-latest  # Use an Ubuntu virtual agent

steps:
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install --with-deps
  displayName: Install dependencies

  - script: |
      wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
      tar -zxvf allure-2.25.0.tgz
      sudo cp -R allure-2.25.0/bin /usr/bin/allure
      export PATH=$PATH:/usr/bin/allure/bin
  displayName: Set up Allure Framework

  - script: |
      pytest
  displayName: Run tests

  - script: |
      allure generate reports/allure-report --clean
  displayName: Generate Allure Report

  - script: |
      ls -la reports/allure-results
      ls -la reports/videos/*
      ls -la logs/trace.zip  # For logging purposes
  displayName: List generated artifacts

  - publish: $(System.DefaultWorkingDirectory)/reports/allure-results  # Publish Allure results
    artifact: allure-results

  - publish: $(System.DefaultWorkingDirectory)/reports/videos/*  # Publish video recordings
    artifact: playwright-videos

  - publish: $(System.DefaultWorkingDirectory)/logs/trace.zip  # Optionally publish logs (for debugging)
    artifact: test-logs