name: Run Tests and Upload Allure Report

on:
  push:
    branches:
      - master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        python -m playwright install --with-deps

        wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
        tar -zxvf allure-2.25.0.tgz
        sudo cp -R allure-2.25.0/bin /usr/bin/allure
        export PATH=$PATH:/usr/bin/allure/bin

    - name: Run tests and Generate Allure Report
      run: |
        pytest
        ls -la
        ls -la reports/
    #     allure generate reports/allure-report --clean

    - name: Archive Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: reports/allure-results
        
    - name: Archive Playwright trace
      uses: actions/upload-artifact@v3
      with:
        name: trace
        path: logs/trace.zip
