name: Run Tests and Upload Allure Report

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        npm install playwright
        playwright install

    - name: Run tests and Generate Allure Report
      run: |
        pytest
        allure generate reports/allure-report --clean

    - name: Archive Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: reports/allure-report
